[package]
name = "lll"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/vityak2k22/LLL_rust_lang_test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
